#!/usr/bin/env bash
# Bootstrap nginx + systemd for the TSA dashboard on Ubuntu / Debian.
#
#   sudo bash deploy/setup.sh
#
# Prompts for:
#   - apex domain
#   - paths to your Cloudflare origin cert + key (paste in advance)
# Installs:
#   - nginx + the dashboard site config (HTTPS, /api proxy, mTLS to CF)
#   - systemd unit running uvicorn on 127.0.0.1:8000
#   - Cloudflare IP allow-list + authenticated origin pull CA
#
# Idempotent: re-run after editing the templates and it will refresh everything.

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "Re-running with sudo..."
  exec sudo bash "$0" "$@"
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# ─── Inputs ─────────────────────────────────────────────────────────────────
read -rp "Apex domain (e.g. tsaedge.com): " DOMAIN
[[ -z "$DOMAIN" ]] && { echo "Domain is required."; exit 1; }

read -rp "Linux user that owns $PROJECT_DIR [${SUDO_USER:-$USER}]: " RUN_USER
RUN_USER="${RUN_USER:-${SUDO_USER:-$USER}}"

# Pick a python: prefer .venv if present, else system python3
if [[ -x "$PROJECT_DIR/.venv/bin/python" ]]; then
  PYTHON="$PROJECT_DIR/.venv/bin/python"
else
  PYTHON="$(command -v python3)"
fi
read -rp "Python binary to run uvicorn [$PYTHON]: " PY_IN
PYTHON="${PY_IN:-$PYTHON}"
[[ ! -x "$PYTHON" ]] && { echo "Not executable: $PYTHON"; exit 1; }

FRONTEND_ROOT="$PROJECT_DIR/dashboard/frontend/dist"

echo
echo "Domain         : $DOMAIN"
echo "Project dir    : $PROJECT_DIR"
echo "Run as user    : $RUN_USER"
echo "Python         : $PYTHON"
echo "SPA root       : $FRONTEND_ROOT"
echo
read -rp "Proceed? [y/N] " yn
[[ "$yn" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 0; }

# ─── Packages ───────────────────────────────────────────────────────────────
echo
echo "── Installing nginx + curl + ca-certificates ──"
apt-get update -qq
DEBIAN_FRONTEND=noninteractive apt-get install -y -qq nginx curl ca-certificates

# ─── Build the frontend (so dist/ exists before nginx tries to serve it) ────
if [[ ! -f "$FRONTEND_ROOT/index.html" ]]; then
  echo "── Building frontend (dist/ missing) ──"
  sudo -u "$RUN_USER" bash -c "cd '$PROJECT_DIR/dashboard/frontend' && npm install --no-fund --no-audit && npx vite build"
fi

# ─── Cloudflare origin cert ─────────────────────────────────────────────────
mkdir -p /etc/ssl/cloudflare
chmod 700 /etc/ssl/cloudflare

if [[ ! -f /etc/ssl/cloudflare/origin.pem || ! -f /etc/ssl/cloudflare/origin.key ]]; then
  cat <<'EOF'

── Cloudflare Origin Certificate ──
Generate one in the Cloudflare dashboard:
  SSL/TLS → Origin Server → Create Certificate
  - RSA 2048, hostnames: $DOMAIN and *.$DOMAIN, 15-year validity
  - Copy the certificate body into:  /etc/ssl/cloudflare/origin.pem
  - Copy the private key body into:  /etc/ssl/cloudflare/origin.key
Then re-run this script.

EOF
  exit 1
fi
chmod 600 /etc/ssl/cloudflare/origin.key
chmod 644 /etc/ssl/cloudflare/origin.pem

# ─── Authenticated Origin Pulls CA (public, published by Cloudflare) ────────
CF_CA=/etc/ssl/cloudflare/authenticated_origin_pull_ca.pem
if [[ ! -s "$CF_CA" ]]; then
  echo "── Downloading Cloudflare Authenticated Origin Pulls CA ──"
  curl -fsSL https://developers.cloudflare.com/ssl/static/authenticated_origin_pull_ca.pem -o "$CF_CA"
fi

# ─── Cloudflare IP allow-list (so real-IP header is trusted) ────────────────
CF_CONF=/etc/nginx/conf.d/cloudflare-ips.conf
echo "── Refreshing Cloudflare IP allow-list ──"
{
  echo "# Auto-generated by deploy/setup.sh — refreshes nginx's view of CF's edge IPs."
  echo "# Run \`sudo bash deploy/setup.sh\` again periodically to update."
  echo
  echo "# IPv4"
  curl -fsSL https://www.cloudflare.com/ips-v4 | sed 's|^|set_real_ip_from |; s|$|;|'
  echo
  echo "# IPv6"
  curl -fsSL https://www.cloudflare.com/ips-v6 | sed 's|^|set_real_ip_from |; s|$|;|'
} > "$CF_CONF"

# ─── nginx site config ─────────────────────────────────────────────────────
NGINX_SITE=/etc/nginx/sites-available/tsa-dashboard.conf
echo "── Writing $NGINX_SITE ──"
sed \
  -e "s|__DOMAIN__|$DOMAIN|g" \
  -e "s|__FRONTEND_ROOT__|$FRONTEND_ROOT|g" \
  "$SCRIPT_DIR/nginx/tsa-dashboard.conf.template" > "$NGINX_SITE"

ln -sf "$NGINX_SITE" /etc/nginx/sites-enabled/tsa-dashboard.conf
# Disable the default site if it's still there.
rm -f /etc/nginx/sites-enabled/default

# nginx needs to read the SPA — give the www-data group traverse access.
# (Files stay owned by $RUN_USER.)
chmod o+x "$PROJECT_DIR"
chmod -R o+rX "$FRONTEND_ROOT"

echo "── nginx -t ──"
nginx -t

# ─── systemd unit for uvicorn ──────────────────────────────────────────────
SYSTEMD_UNIT=/etc/systemd/system/tsa-dashboard-api.service
echo "── Writing $SYSTEMD_UNIT ──"
sed \
  -e "s|__USER__|$RUN_USER|g" \
  -e "s|__PROJECT_DIR__|$PROJECT_DIR|g" \
  -e "s|__PYTHON__|$PYTHON|g" \
  "$SCRIPT_DIR/systemd/tsa-dashboard-api.service.template" > "$SYSTEMD_UNIT"

systemctl daemon-reload
systemctl enable --now tsa-dashboard-api.service
systemctl restart tsa-dashboard-api.service

# Wait briefly for the port to come up before we reload nginx
for _ in {1..10}; do
  ss -ltn 'sport = :8000' 2>/dev/null | grep -q ':8000' && break
  sleep 0.5
done

systemctl reload nginx || systemctl restart nginx

echo
echo "── Done ──"
echo "  Backend  : systemctl status tsa-dashboard-api"
echo "  Logs     : journalctl -u tsa-dashboard-api -f"
echo "  nginx    : journalctl -u nginx -f"
echo
echo "Next:"
echo "  1. In Cloudflare DNS, add A records for @ and www → your VM's public IP (Proxy = ON, orange cloud)."
echo "  2. SSL/TLS → Overview: set encryption mode to 'Full (strict)'."
echo "  3. SSL/TLS → Origin Server → Authenticated Origin Pulls: enable for $DOMAIN."
echo "  4. Visit https://$DOMAIN"
